import { CheckCircle2, CircleAlert, FileText, FolderKanban, ListChecks, MessageSquareText } from "lucide-react";
import { Button } from "../../shared/ui/Button";
import { JobAnalysisStatus } from "./JobAnalysisStatus";
import type { JobAnalysis, JobTarget, JobTargetRetrospectiveSummary, TargetReadiness } from "./jobTargetTypes";

const labels: Record<string, string> = { requirements_pending: "先确认岗位要求", project_selection_pending: "选择重点准备项目", deep_dive_in_progress: "继续项目深挖", high_risk_open: "处理尚未掌握的项目问题", core_preparation_complete: "核心准备已完成" };

export function JobTargetOverview({ target, readiness, analysis, retrospectiveSummary, onEditJd, onStartAnalysis, onControl, onNavigate, onOpenRetrospectives }: { target: JobTarget; readiness?: TargetReadiness; analysis?: JobAnalysis | null; retrospectiveSummary?: JobTargetRetrospectiveSummary; onEditJd: () => void; onStartAnalysis: () => void; onControl: (action: "pause" | "resume" | "terminate") => void; onNavigate: (tab: "requirements" | "deep-dive" | "review") => void; onOpenRetrospectives: () => void }) {
  const nextTab = readiness?.status === "requirements_pending" ? "requirements" : readiness?.status === "project_selection_pending" || readiness?.status === "deep_dive_in_progress" ? "deep-dive" : "review";
  const gaps = Object.entries(retrospectiveSummary?.gapCounts ?? {}).sort((left, right) => right[1] - left[1]);
  return <div className="job-target-overview"><section className="job-target-overview__lead"><div><span>下一步</span><h2>{target.currentDocumentVersionId ? labels[readiness?.status ?? "requirements_pending"] : "先添加岗位描述"}</h2><p>围绕岗位要求核对个人经历，再把重点项目练成能讲、能追问、能复盘的面试答案。</p></div><div className="job-target-overview__lead-actions">{target.currentDocumentVersionId ? <><Button variant="secondary" onClick={onStartAnalysis}>重新分析</Button><Button onClick={() => onNavigate(nextTab)}>继续准备</Button></> : <Button onClick={onEditJd}><FileText size={16} />添加岗位描述</Button>}</div></section>{analysis ? <JobAnalysisStatus analysis={analysis} onControl={onControl} onOpenRequirements={() => onNavigate("requirements")} onOpenProjects={() => onNavigate("deep-dive")} /> : null}<section className="job-target-overview__steps"><button type="button" onClick={() => onNavigate("requirements")}><ListChecks /><div><strong>1. 看懂岗位</strong><p>{readiness?.requirements ?? 0} 条岗位要求</p></div></button><button type="button" onClick={() => onNavigate("deep-dive")}><FolderKanban /><div><strong>2. 选重点项目</strong><p>1 个核心项目，最多 2 个补充项目</p></div></button><button type="button" onClick={() => onNavigate("review")}>{readiness?.status === "core_preparation_complete" ? <CheckCircle2 /> : <CircleAlert />}<div><strong>3. 练项目问题</strong><p>确认候选题后进入项目经历题分类</p></div></button></section><section className="job-target-overview__retrospectives"><header><div><MessageSquareText size={18} /><span>面试反馈</span></div><Button size="sm" variant="secondary" onClick={onOpenRetrospectives}>{retrospectiveSummary?.retrospectiveCount ? "查看全部复盘" : "开始第一次复盘"}</Button></header>{retrospectiveSummary?.retrospectiveCount ? <><div className="job-target-overview__retrospective-metrics"><div><strong>{retrospectiveSummary.retrospectiveCount}</strong><span>场复盘</span></div><div><strong>{retrospectiveSummary.latest?.roundLabel ?? "—"}</strong><span>最近一轮 · {retrospectiveSummary.latest?.outcome === "passed" ? "通过" : retrospectiveSummary.latest?.outcome === "failed" ? "未通过" : "结果待记录"}</span></div><div><strong>{retrospectiveSummary.unresolvedActionCount}</strong><span>项还要准备</span></div></div>{gaps.length ? <p>反复出现的短板：{gaps.slice(0, 3).map(([kind, count]) => `${gapLabel(kind)} ${count}`).join(" · ")}</p> : <p>目前没有未解决的能力短板。</p>}</> : <div className="job-target-overview__retrospective-empty"><strong>还没有面试反馈</strong><p>面试后粘贴转写或回忆，逐轮积累这个岗位的真实反馈。</p></div>}</section></div>;
}

function gapLabel(kind: string) {
  return ({ material: "素材", expression: "表达", knowledge: "知识", experience: "经历" } as Record<string, string>)[kind] ?? kind;
}
